version: '3.8'

services:
  ai-core:
    build: ./ai-core
    container_name: ai-core
    volumes:
      - ./ai-core:/app
      - ./chroma_data:/data
    ports:
      - "8000:8000"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8001
    depends_on:
      - chroma

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8001:8001"
    volumes:
      - ./chroma_data:/data
